'use client';

// import type { Metadata } from 'next';
import { DebugLogProvider } from '@/hooks/useDebugLog';
import '../styles/globals.css';
import { useState } from 'react';
import { DialogCountContext } from '@/components/shared/DialogCountContext';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const dialogState = useState<number>(0);
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className="font-default antialiased">
        <DialogCountContext.Provider value={dialogState}>
          <DebugLogProvider>{children}</DebugLogProvider>
        </DialogCountContext.Provider>
      </body>
    </html>
  );
}
