import type { Metadata } from 'next';
import { Noto_Serif_JP } from 'next/font/google';
import '../styles/globals.css';

const notoSerifJP = Noto_Serif_JP({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSerifJP.className} antialiased`}>{children}</body>
    </html>
  );
}
