import type { Metadata } from 'next';
import { DebugLogProvider } from '@/hooks/useDebugLog';
import '../styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className="font-default antialiased">
        <DebugLogProvider>{children}</DebugLogProvider>
      </body>
    </html>
  );
}
